/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Recepcioner;
import java.awt.Color;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import logika.Kontroler;
import modeli.ModelTabeleRecepcioner;
import server.PokretanjeServeraNit;
import util.DBUtil;

/**
 *
 * @author Marjan
 */
public class FGlavna extends javax.swing.JFrame {

    PokretanjeServeraNit psn;

    /**
     * Creates new form FGlavna
     */
    public FGlavna() {
        initComponents();
        setTitle("Serverska forma");
        srediFormuPreStartovanja();
        srediTabelu();
        tableRecepcioneri.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBrojPorta = new javax.swing.JTextField();
        btnPokreni = new javax.swing.JButton();
        btnZaustavi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRecepcioneri = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemKonekcija = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Unesite broj porta:");

        txtBrojPorta.setText("9000");

        btnPokreni.setText("Pokreni server");
        btnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniActionPerformed(evt);
            }
        });

        btnZaustavi.setText("Zaustavi server");
        btnZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviActionPerformed(evt);
            }
        });

        tableRecepcioneri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableRecepcioneri);

        jMenu1.setText("Konekcija na bazu");

        menuItemKonekcija.setText("Konekcija");
        menuItemKonekcija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKonekcijaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemKonekcija);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPokreni, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBrojPorta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZaustavi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBrojPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPokreni)
                    .addComponent(btnZaustavi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniActionPerformed
        if (txtBrojPorta.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite broj porta!");
            txtBrojPorta.setBorder(BorderFactory.createLineBorder(Color.red));
            return;
        }

        txtBrojPorta.setBorder(BorderFactory.createEtchedBorder());

        int port = -1;
        try {
            port = Integer.parseInt(txtBrojPorta.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Unesite broj!");
            txtBrojPorta.setBorder(BorderFactory.createLineBorder(Color.red));
            return;
        }

        txtBrojPorta.setBorder(BorderFactory.createEtchedBorder());
        if (port < 0 || port > 65535) {
            JOptionPane.showMessageDialog(this, "Broj porta nije u odgovarajucem opsegu. Preporuceno (1024-65535)");
            txtBrojPorta.setBorder(BorderFactory.createLineBorder(Color.red));
            return;
        }

        txtBrojPorta.setBorder(BorderFactory.createEtchedBorder());

        DBUtil dbUtil;
        String portIzFilea = "";
        try {
            dbUtil = new DBUtil();
            dbUtil.setPort(port);
            portIzFilea = dbUtil.vratiPort();
        } catch (IOException ex) {
            Logger.getLogger(FGlavna.class.getName()).log(Level.SEVERE, null, ex);
        }

        psn = new PokretanjeServeraNit(this, Integer.parseInt(portIzFilea));
        psn.start();
        JOptionPane.showMessageDialog(this, "Server je pokrenut.");

        txtBrojPorta.setEnabled(false);
        btnPokreni.setEnabled(false);
        btnZaustavi.setEnabled(true);
        tableRecepcioneri.setVisible(true);

    }//GEN-LAST:event_btnPokreniActionPerformed

    private void btnZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviActionPerformed
        psn.interrupt();
        JOptionPane.showMessageDialog(this, "Server je zaustavljen.");

        srediFormuPreStartovanja();

    }//GEN-LAST:event_btnZaustaviActionPerformed

    private void menuItemKonekcijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKonekcijaActionPerformed
        FKonekcijaNaBazu fknb = new FKonekcijaNaBazu();
        fknb.setVisible(true);
    }//GEN-LAST:event_menuItemKonekcijaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreni;
    private javax.swing.JButton btnZaustavi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuItemKonekcija;
    private javax.swing.JTable tableRecepcioneri;
    private javax.swing.JTextField txtBrojPorta;
    // End of variables declaration//GEN-END:variables

    public void srediTabelu() {

        tableRecepcioneri.setVisible(true);
        List<Recepcioner> listaRecepcionera = Kontroler.getInstanca().getListaRecepcioneraIzBaze();

        ModelTabeleRecepcioner mtr = new ModelTabeleRecepcioner(listaRecepcionera);
        tableRecepcioneri.setModel(mtr);

    }

    private void srediFormuPreStartovanja() {
        btnPokreni.setEnabled(true);
        btnZaustavi.setEnabled(false);
        tableRecepcioneri.setVisible(false);
    }
}
