/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import database.Konekcija;
import java.awt.Color;
import java.io.IOException;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import util.DBUtil;

/**
 *
 * @author Marjan
 */
public class FKonekcijaNaBazu extends javax.swing.JFrame {

    /**
     * Creates new form KonekcijaNaBazu
     */
    public FKonekcijaNaBazu() {
        initComponents();
        setTitle("Konekcija na bazu");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        btnKonektujSe = new javax.swing.JButton();
        passWord = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Url:");

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        btnKonektujSe.setText("Konektuj se");
        btnKonektujSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonektujSeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnKonektujSe))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(txtUsername)
                            .addComponent(passWord))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnKonektujSe)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonektujSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonektujSeActionPerformed
        String url = txtUrl.getText().trim();
        String username = txtUsername.getText().trim();
        String password = String.valueOf(passWord.getPassword());

        try {
            validacija(url, username);
            DBUtil dbUtil;
            String urlIzFilea = null;
            String usernameIzFilea = null;
            String passwordIzFilea = null;
            try {
                dbUtil = new DBUtil();
                dbUtil.setUrl(url);
                dbUtil.setUser(username);
                dbUtil.setPassword(password);
                System.out.println(dbUtil.vratiDBURL());
                urlIzFilea = dbUtil.vratiDBURL();
                usernameIzFilea = dbUtil.vratiDBKorisnik();
                passwordIzFilea = dbUtil.vratiDBSifra();
                Connection konekcija = Konekcija.vratiObjekat().vratiKonekciju();
               
                JOptionPane.showMessageDialog(this, "Uspesno ste se konektovali na bazu!");
                FGlavna fg = new FGlavna();
                dispose();
                fg.setVisible(true);
                
            } catch (IOException ex) {
            }

        } catch (Exception ex) {
            Logger.getLogger(FKonekcijaNaBazu.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnKonektujSeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FKonekcijaNaBazu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FKonekcijaNaBazu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FKonekcijaNaBazu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FKonekcijaNaBazu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FKonekcijaNaBazu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonektujSe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JTextField txtUrl;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void validacija(String url, String username) throws Exception {
        if ((username == null || username.isEmpty()) && (url == null || url.isEmpty())) {
            Border border = BorderFactory.createLineBorder(Color.red);
            txtUsername.setBorder(border);
            txtUrl.setBorder(border);
            throw new Exception("Morate uneti url i username!");
        } else {
            txtUrl.setBorder(BorderFactory.createEtchedBorder());;
            txtUsername.setBorder(BorderFactory.createEtchedBorder());
        }

        if (username == null || username.isEmpty()) {
            Border border = BorderFactory.createLineBorder(Color.red);
            txtUsername.setBorder(border);
            throw new Exception("Morate uneti username!");
        } else {
            txtUsername.setBorder(BorderFactory.createEtchedBorder());
        }

        if (url == null || url.isEmpty()) {
            Border border = BorderFactory.createLineBorder(Color.red);
            txtUrl.setBorder(border);
            throw new Exception("Morate uneti url!");
        } else {
            txtUrl.setBorder(BorderFactory.createEtchedBorder());
        }
    }
}
