/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Recepcioner;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logika.Kontroler;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Marjan
 */
public class FGlavna extends javax.swing.JFrame {

    private Recepcioner logovani;

    /**
     * Creates new form FGlavna
     */
    public FGlavna() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    public FGlavna(Recepcioner r) {
        initComponents();
        logovani = r;
        this.setExtendedState(MAXIMIZED_BOTH);
        logovani = r;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        txtLogovaniRecepcioner = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuUnosGosta = new javax.swing.JMenuItem();
        menuPretragaGosta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuPretragaSoba = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        meniUnosNovogIzdavanja = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txtLogovaniRecepcioner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnLogOut.setText("LOG OUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jMenu2.setText("Gost");

        menuUnosGosta.setText("Unos novog gosta");
        menuUnosGosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUnosGostaActionPerformed(evt);
            }
        });
        jMenu2.add(menuUnosGosta);

        menuPretragaGosta.setText("Pretraga gostiju");
        menuPretragaGosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPretragaGostaActionPerformed(evt);
            }
        });
        jMenu2.add(menuPretragaGosta);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sobe");

        menuPretragaSoba.setText("Pretraga soba");
        menuPretragaSoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPretragaSobaActionPerformed(evt);
            }
        });
        jMenu3.add(menuPretragaSoba);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Izdavanje soba");

        meniUnosNovogIzdavanja.setText("Unos novog izdavanja sobe");
        meniUnosNovogIzdavanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniUnosNovogIzdavanjaActionPerformed(evt);
            }
        });
        jMenu5.add(meniUnosNovogIzdavanja);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtLogovaniRecepcioner, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 192, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLogovaniRecepcioner, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuUnosGostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUnosGostaActionPerformed
        FUnosNovogGosta fung = new FUnosNovogGosta(this, true);
        fung.setVisible(true);


    }//GEN-LAST:event_menuUnosGostaActionPerformed

    private void menuPretragaGostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPretragaGostaActionPerformed
        try {
            FPretragaGostiju fpg = new FPretragaGostiju(this, true);
            fpg.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FGlavna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuPretragaGostaActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        Kontroler.getInstanca().logout(logovani, this);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Kontroler.getInstanca().logout(logovani, this);
    }//GEN-LAST:event_formWindowClosing

    private void menuPretragaSobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPretragaSobaActionPerformed
        try {
            FPretragaSoba fps = new FPretragaSoba(this, true);
            fps.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FGlavna.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_menuPretragaSobaActionPerformed

    private void meniUnosNovogIzdavanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniUnosNovogIzdavanjaActionPerformed
        FUnosNovogIzdavanjaSobe funis = new FUnosNovogIzdavanjaSobe(this, true);
        funis.setVisible(true);
    }//GEN-LAST:event_meniUnosNovogIzdavanjaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem meniUnosNovogIzdavanja;
    private javax.swing.JMenuItem menuPretragaGosta;
    private javax.swing.JMenuItem menuPretragaSoba;
    private javax.swing.JMenuItem menuUnosGosta;
    private javax.swing.JLabel txtLogovaniRecepcioner;
    // End of variables declaration//GEN-END:variables

    void postaviRecepcionera(Recepcioner logovaniRecepcioner) {
        txtLogovaniRecepcioner.setText("Ulogovani ste kao: " + logovaniRecepcioner.getIme() + " " + logovaniRecepcioner.getPrezime());
    }

    public void uspesanLogou(ServerskiOdgovor so) {
        JOptionPane.showMessageDialog(this, so.getPoruka());
        this.setVisible(false);
        FPocetna fp = new FPocetna();
        fp.setVisible(true);
    }

    public void neuspesanLogou(ServerskiOdgovor so) {
        JOptionPane.showMessageDialog(this, so.getPoruka());
    }

    public Recepcioner getLogovani() {
        return logovani;
    }

    
    
}
