/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Recepcioner;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import logika.Kontroler;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Marjan
 */
public class FLogin extends javax.swing.JFrame {
    
    String ipAdresa;
    int port;

    /**
     * Creates new form FLogin
     */
    public FLogin() {
        initComponents();
        setTitle("Login");
        this.ipAdresa = ipAdresa;
        this.port = port;
        setLocationRelativeTo(null);
    }
    
    public FLogin(String adresa, int port) {
        initComponents();
        setTitle("Login");
        this.ipAdresa = adresa;
        this.port = port;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        passwordPolje = new javax.swing.JPasswordField();
        btnPrijaviSe = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        txtUsername.setText("mar");

        btnPrijaviSe.setText("Prijavi se");
        btnPrijaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrijaviSeActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrijaviSe, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordPolje, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(txtUsername))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordPolje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrijaviSe)
                    .addComponent(btnOdustani))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrijaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrijaviSeActionPerformed
        String username = txtUsername.getText().trim();
        String password = String.valueOf(passwordPolje.getPassword());
        
        try {
            validacija(username, password);
            
            Recepcioner r = new Recepcioner();
            r.setKorisnickoIme(username);
            r.setSifra(password);
            Recepcioner logovaniRecepcioner = Kontroler.getInstanca().pronadjiRecepcioneraLogin(r);
            if (logovaniRecepcioner == null) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da pronadje recepcionera na osnovu unetih vrednosti");
                txtUsername.setBorder(BorderFactory.createLineBorder(Color.RED));
                passwordPolje.setBorder(BorderFactory.createLineBorder(Color.RED));
            } else {
                Kontroler.getInstanca().uloguj(logovaniRecepcioner, this);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greska" + e.getMessage());
        }

    }//GEN-LAST:event_btnPrijaviSeActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        FPocetna fp = new FPocetna();
        fp.postaviVrednosti(ipAdresa, port);
        this.dispose();
        fp.setVisible(true);
        

    }//GEN-LAST:event_btnOdustaniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnPrijaviSe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passwordPolje;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void validacija(String username, String password) throws Exception {
        Border border = BorderFactory.createLineBorder(Color.red);
        
        if ((username == null || username.isEmpty()) && (password == null || password.isEmpty())) {
            txtUsername.setBorder(border);
            passwordPolje.setBorder(border);
            throw new Exception("Sva polja su obavezna!");
        } else {
            txtUsername.setBorder(BorderFactory.createEtchedBorder());
            passwordPolje.setBorder(BorderFactory.createEtchedBorder());
        }
        
        if (username == null || username.isEmpty()) {
            txtUsername.setBorder(border);
            throw new Exception("Morate uneti username!");
        } else {
            txtUsername.setBorder(BorderFactory.createEtchedBorder());
        }
        
        if (password == null || password.isEmpty()) {
            passwordPolje.setBorder(border);
            throw new Exception("Morate uneti password!");
        } else {
            passwordPolje.setBorder(BorderFactory.createEtchedBorder());
        }
        
    }
    
    public void uspesno(ServerskiOdgovor so, Recepcioner logovaniRecepcioner) {
        JOptionPane.showMessageDialog(this, so.getPoruka());
        FGlavna fg = new FGlavna(logovaniRecepcioner);
        fg.postaviRecepcionera(logovaniRecepcioner);
        dispose();
        fg.setVisible(true);
    }
    
    public void neuspesno(ServerskiOdgovor so) {
        JOptionPane.showMessageDialog(this, so.getPoruka());
    }
}
