/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Gost;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import logika.Kontroler;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Marjan
 */
public class FUnosNovogGosta extends javax.swing.JDialog {

    /**
     * Creates new form UnosNovogGosta
     */
    public FUnosNovogGosta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Gost");
        initComponents();
        setLocationRelativeTo(null);
        checkSmesten.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtBrojTelefona = new javax.swing.JTextField();
        checkSmesten = new javax.swing.JCheckBox();
        btnSacuvaj = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime:");

        jLabel3.setText("Broj telefona:");

        txtBrojTelefona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBrojTelefonaKeyReleased(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel5.setText("Unos novog Gosta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrezime)
                            .addComponent(txtBrojTelefona)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkSmesten)
                                .addGap(0, 240, Short.MAX_VALUE))
                            .addComponent(txtIme)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(checkSmesten)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(btnSacuvaj)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        String brojTel = txtBrojTelefona.getText().trim();
        boolean smesten = checkSmesten.isSelected();
        try {
            validacija(ime, prezime, brojTel);
            //validaciju ubaci
            int id = Kontroler.getInstanca().vratiIDGosta();
            Gost gost = new Gost(id, ime, prezime, brojTel, smesten);
            //vrati listu svih gostiju iz baze da bi video da li vec postoji  
            List<Gost> listaGostiju = Kontroler.getInstanca().vratiGoste();

            for (Gost g : listaGostiju) {
                if (g.getIme().equals(ime) && g.getPrezime().equals(prezime) && g.getBrTel().equals(brojTel)) {
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti gosta!");
                    return;
                }
            }

            Kontroler.getInstanca().sacuvajGosta(gost, this);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greska: " + e.getMessage());

        }


    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void txtBrojTelefonaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrojTelefonaKeyReleased
        String brojTelefona = txtBrojTelefona.getText().trim();
        
        for (char c : brojTelefona.toCharArray()) {
            if(!Character.isDigit(c) && !brojTelefona.isEmpty()){
                JOptionPane.showMessageDialog(this, "Broj telefona moze sadrzati samo cifre!");
                txtBrojTelefona.setText("");
            }
        }
    }//GEN-LAST:event_txtBrojTelefonaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FUnosNovogGosta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FUnosNovogGosta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FUnosNovogGosta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FUnosNovogGosta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FUnosNovogGosta dialog = new FUnosNovogGosta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JCheckBox checkSmesten;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtBrojTelefona;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    public void uspesno() {
        JOptionPane.showMessageDialog(this, "Sistem je zapamtio gosta!");
    }

    public void neuspesno(ServerskiOdgovor so) {
        JOptionPane.showMessageDialog(this, so.getPoruka());
    }

    private void validacija(String ime, String prezime, String brojTel) throws Exception {
        Border a = BorderFactory.createEtchedBorder();
        Border b = BorderFactory.createLineBorder(Color.RED);

        txtIme.setBorder(a);
        txtPrezime.setBorder(a);
        txtBrojTelefona.setBorder(a);

        //  txtIme txtPrezime txtBrojTelefona
        //|| txtIme == null
        //|| txtPrezime == null
        //|| txtBrojTelefona == null
        if ((ime.isEmpty() || ime == null) && (prezime.isEmpty() || prezime == null) && (brojTel.isEmpty() || brojTel == null)) {
            txtIme.setBorder(b);
            txtPrezime.setBorder(b);
            txtBrojTelefona.setBorder(b);
            throw new Exception("Sva tekstualna polja moraju biti popunjena!");
        }

        if (!(ime.isEmpty() || ime == null) && (prezime.isEmpty() || prezime == null) && (brojTel.isEmpty() || brojTel == null)) {
            txtPrezime.setBorder(b);
            txtBrojTelefona.setBorder(b);
            throw new Exception("Sva tekstualna polja moraju biti popunjena!");
        }
        if ((ime.isEmpty() || ime == null) && !(prezime.isEmpty() || prezime == null) && (brojTel.isEmpty() || brojTel == null)) {
            txtIme.setBorder(b);
            txtBrojTelefona.setBorder(b);
            throw new Exception("Sva tekstualna polja moraju biti popunjena!");
        }
        if ((ime.isEmpty() || ime == null) && (prezime.isEmpty() || prezime == null) && !(brojTel.isEmpty() || brojTel == null)) {
            txtIme.setBorder(b);
            txtPrezime.setBorder(b);
            throw new Exception("Sva tekstualna polja moraju biti popunjena!");
        }

        if ((ime.isEmpty() || ime == null) && !(prezime.isEmpty() || prezime == null) && !(brojTel.isEmpty() || brojTel == null)) {
            txtIme.setBorder(b);
            throw new Exception("Sva tekstualna polja moraju biti popunjena!");
        }
        if (!(ime.isEmpty() || ime == null) && (prezime.isEmpty() || prezime == null) && !(brojTel.isEmpty() || brojTel == null)) {
            txtPrezime.setBorder(b);
            throw new Exception("Sva tekstualna polja moraju biti popunjena!");
        }
        if (!(ime.isEmpty() || ime == null) && !(prezime.isEmpty() || prezime == null) && (brojTel.isEmpty() || brojTel == null)) {
            txtBrojTelefona.setBorder(b);
            throw new Exception("Sva tekstualna polja moraju biti popunjena!");
        }
    }
}
